server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
